### ISSUE TITLE
Location of grafana template

### ISSUE THREAD

**Issue by abhay40711cs** [AdysTech/Influxer#27]
Please update the location of grafana template

**Comment by mvadu** [comment]
Thanks for noticing. I have updated [wiki](https://github.com/AdysTech/Influxer/wiki/Setting-up-Grafana-dashboard-to-visualize-Perfmon-logs), as well as a separate [page for template](https://github.com/AdysTech/Influxer/wiki/Perfmon-Visualization-grafana-template) is added.
