### ISSUE TITLE
Mili second is showing z in the end 

### ISSUE THREAD

**Issue by abhay40711cs** [AdysTech/Influxer#28]
2017-08-21T10:58:12Z | 3.95 | 1632.31 | 77.9 | 10521.76
-- | -- | -- | -- | --

**Comment by mvadu** [comment]
@abhay40711cs where are you seeing the Z? From Influx query output? that Z essentially means the time is in UTC. If you are querying then you need to specify the precision manually, otherwise default query output shows only up to sec.

**Comment by abhay40711cs** [comment]
It was on Query output,  Time is not showing the last milisecond digit.  Thereby i suspect it was unable to plot it on Grafana.
time | C1_Time | C1_Transitions_sec | C2_Time | C2_Transitions_sec | C3_Time | C3_Transitions_sec | DPC_Rate | DPC_Time | DPCs_Queued_sec | Host | Idle_Time | Interrupt_Time | Interrupts_sec | Privileged_Time | Processor_Time | User_Time | application
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2017-08-21T10:57:55Z | 1.06 | 389.36 | 88.71 | 4080.12 | 0 | 0 | 8 | 0 | 291 | "PC-ABHAYK" | 93.64 | 0 | 4141.97 | 2.77 | 6.36 | 3.16 | "appname"

Would you please give me sample example to setup grafana query on above scenario,

**Comment by mvadu** [comment]
As I mentioned the default query output formats the data to a second precision. You need to query with `epoch=ms` query parameter to get the actual ms level details. Or [use the grafana dashboard](https://github.com/AdysTech/Influxer/wiki/Setting-up-Grafana-dashboard-to-visualize-Perfmon-logs) to visualize.
