### ISSUE TITLE
Issues with arguments

### ISSUE THREAD

**Issue by R-Sommer** [AdysTech/Influxer#29]
Trying to print possible config section fails: Influxer.exe /export
&nbsp;&nbsp;&nbsp;Error processing arguments NullReferenceException: Object reference not set to an instance of an object.

Trying to add some parameters fails i.e.: Influxer.exe -uname test
&nbsp;&nbsp;&nbsp;Error processing arguments :ArgumentException, Invalid commandline arguments!! Use /help to see valid ones

Trying to add some more parameters fails i.e.: Influxer.exe -format Perfmon -input \Bench\Test01.csv -influx http://192.168.1.7:8086 -dbName Perfmon -uname test
&nbsp;&nbsp;&nbsp;Unknown command line arguments: -influx, -dbname, -uname

**Comment by mvadu** [comment]
i am able to recreate it. Will fix it along with next minor release.

**Comment by mvadu** [comment]
Fixed in #30, should produce as shown in latest [Influxer.Test.InfluxerTests.TestExportCommand](https://ci.appveyor.com/project/AdysTech/influxer/build/0.11-epciofsi/tests)
