### ISSUE TITLE
'Can't parse as Number' error

### ISSUE THREAD

**Issue by dvkalashnikov** [AdysTech/Influxer#33]
I have a case when influxDB 1.7.8-1 and Influxer latest version couldn't parse the data from CSV and fails with the following error:

d:\Downloads\Grafana\InfluxerLatest>Influxer.exe -input "MP_DataCollector.csv"
Failed to process d:\Downloads\Grafana\InfluxerLatest\MP_DataCollector.csv
Error!! InvalidDataException:\\SCOM2016\Process_wmiprvse_\_Processor_Time has inconsistent data, Can't parse 0.15612238088219549 as Number -    at AdysTech.Influxer.GenericFile.ValidateData(String InputFileName) in C:\projects\influxer\Influxer\GenericFile.cs:line 497
   at AdysTech.Influxer.GenericFile.<ProcessGenericFile>d__13.MoveNext() in C:\projects\influxer\Influxer\GenericFile.cs:line 245
 Finished!! Processed 0 points (Success: 0, Failed:0) in 00:00:00.4922178

It looks like some kind of incompatibility on my PC because on the other PC everything went well with the same CSV file.
Could you please take a look at this error?

**Comment by mvadu** [comment]
if possible can you please attach a sample file? may be first 500 lines..

**Comment by dvkalashnikov** [comment]
@mvadu Sure. Here you go:
https://1drv.ms/u/s!AlulvKmJWjwr9wZZA-dKrAJX0fCq?e=5BpEDX

**Comment by dvkalashnikov** [comment]
Hi @mvadu, any updates?

**Comment by mvadu** [comment]
been busy with personal and professional commitments. Will get to this by Thursday hopefully.

**Comment by mvadu** [comment]
hi @dvkalashnikov i think the file you shared seems to have been expired. Can you please share it again.. sorry for the delay in getting to it.

**Comment by dvkalashnikov** [comment]
@mvadu sure, updated:
https://1drv.ms/u/s!AlulvKmJWjwrgYRafNg8URh3A18GZg?e=Uh3qj3

**Comment by mvadu** [comment]
Finally I got to this today. I tried running the Perfmon test using your data, and it went through without any errors.
![image](https://user-images.githubusercontent.com/8618235/73584086-0c2e4a00-4464-11ea-9f0f-535c3ced9784.png)

Since you mentioned in one machine it failed, and worked in another one, do you know if you have different windows locale in either of them?

**Comment by dvkalashnikov** [comment]
@mvadu thanks for your investigation, actually the Windows display language the same - EN-US, and what else besides this can affect such an error?
